### ISSUE TITLE
pip install -r requirements.txt, issue with tensorflow

### ISSUE THREAD

**Issue by lukkio88** [anuragranj/coma#13]
Hi, when I try to run

```
pip install -r requirements.txt
```

I get the error:

```  Could not find a version that satisfies the requirement tensorflow-gpu==1.3.0 (from -r requirements.txt (line 7)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 2.0.0a0)
No matching distribution found for tensorflow-gpu==1.3.0 (from -r requirements.txt (line 7))```

However I've already installed tensorflow and tensorflow gpu, I can spot what the issue is.
I've tried to hack your requirement file (essentially just removing the version) it still doesn't work.

Can you help?

**Comment by anuragranj** [comment]
If tensorflow is already installed, then you just remove the tensorflow-gpu==1.3.0 from the requirements.txt, install the other dependencies, and then try to run the code.

**Comment by lukkio88** [comment]
In such a case I get:

```
Building wheels for collected packages: opendr
  Running setup.py bdist_wheel for opendr ... error
  Complete output from command /home/SERILOCAL/l.gagliano/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7le0ae6k/opendr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-69ytynvx --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/opendr
  copying opendr/cvwrap.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/occlusion_test.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/geometry.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/lighting.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/slider_demo.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/simple.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/util_tests.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/test_camera.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/renderer.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/camera.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/test_geometry.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/dummy.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/test_depth_renderer.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/everything.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/test_renderer.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/__init__.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/common.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/topology.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/test_sh.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/serialization.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/version.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/filters.py -> build/lib.linux-x86_64-3.7/opendr
  copying opendr/utils.py -> build/lib.linux-x86_64-3.7/opendr
  creating build/lib.linux-x86_64-3.7/opendr/contexts
  copying opendr/contexts/draw_triangle_shaders_3_2.py -> build/lib.linux-x86_64-3.7/opendr/contexts
  copying opendr/contexts/fix_warnings.py -> build/lib.linux-x86_64-3.7/opendr/contexts
  copying opendr/contexts/autogen.py -> build/lib.linux-x86_64-3.7/opendr/contexts
  copying opendr/contexts/__init__.py -> build/lib.linux-x86_64-3.7/opendr/contexts
  copying opendr/contexts/_constants.py -> build/lib.linux-x86_64-3.7/opendr/contexts
  copying opendr/contexts/draw_triangle_shaders_2_1.py -> build/lib.linux-x86_64-3.7/opendr/contexts
  creating build/lib.linux-x86_64-3.7/opendr/test_dr
  copying opendr/test_dr/__init__.py -> build/lib.linux-x86_64-3.7/opendr/test_dr
  running build_ext
  building 'opendr.contexts.ctx_mesa' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/opendr
  creating build/temp.linux-x86_64-3.7/opendr/contexts
  gcc -pthread -B /home/SERILOCAL/l.gagliano/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D__OSMESA__=1 -Iopendr/contexts -I. -I/home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include -Iopendr/contexts/OSMesa/include -I/home/SERILOCAL/l.gagliano/anaconda3/include/python3.7m -c opendr/contexts/ctx_mesa.c -o build/temp.linux-x86_64-3.7/opendr/contexts/ctx_mesa.o -lstdc++
  In file included from /home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:0,
                   from /home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from opendr/contexts/ctx_mesa.c:660:
  /home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  In file included from opendr/contexts/ctx_mesa.c:663:0:
  opendr/contexts/OSMesa/include/GL/osmesa.h:258:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   typedef void (*OSMESAproc)();
   ^
  opendr/contexts/ctx_mesa.c: In function ‘__pyx_pf_6opendr_8contexts_8ctx_mesa_13OsContextBase_150ShaderSource’:
  opendr/contexts/ctx_mesa.c:12788:49: warning: passing argument 3 of ‘glShaderSource’ from incompatible pointer type [-Wincompatible-pointer-types]
     glShaderSource(__pyx_v_shader, __pyx_v_count, (&__pyx_v_s), (&__pyx_v_len));
                                                   ^
  In file included from opendr/contexts/OSMesa/include/GL/gl.h:2085:0,
                   from opendr/contexts/gl_includes.h:10,
                   from opendr/contexts/ctx_mesa.c:662:
  opendr/contexts/OSMesa/include/GL/glext.h:5794:21: note: expected ‘const GLchar ** {aka const char **}’ but argument is of type ‘char **’
   GLAPI void APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar* *string, const GLint *length);
                       ^
  gcc -pthread -shared -B /home/SERILOCAL/l.gagliano/anaconda3/compiler_compat -L/home/SERILOCAL/l.gagliano/anaconda3/lib -Wl,-rpath=/home/SERILOCAL/l.gagliano/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/opendr/contexts/ctx_mesa.o -Lopendr/contexts/OSMesa/lib -lOSMesa -lGL -lGLU -o build/lib.linux-x86_64-3.7/opendr/contexts/ctx_mesa.cpython-37m-x86_64-linux-gnu.so -lstdc++
  /home/SERILOCAL/l.gagliano/anaconda3/compiler_compat/ld: cannot find -lOSMesa
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for opendr
  Running setup.py clean for opendr
Failed to build opendr
Installing collected packages: opendr, readchar
  Running setup.py install for opendr ... error
    Complete output from command /home/SERILOCAL/l.gagliano/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7le0ae6k/opendr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-31er561u/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/opendr
    copying opendr/cvwrap.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/occlusion_test.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/geometry.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/lighting.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/slider_demo.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/simple.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/util_tests.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/test_camera.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/renderer.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/camera.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/test_geometry.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/dummy.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/test_depth_renderer.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/everything.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/test_renderer.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/__init__.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/common.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/topology.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/test_sh.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/serialization.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/version.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/filters.py -> build/lib.linux-x86_64-3.7/opendr
    copying opendr/utils.py -> build/lib.linux-x86_64-3.7/opendr
    creating build/lib.linux-x86_64-3.7/opendr/contexts
    copying opendr/contexts/draw_triangle_shaders_3_2.py -> build/lib.linux-x86_64-3.7/opendr/contexts
    copying opendr/contexts/fix_warnings.py -> build/lib.linux-x86_64-3.7/opendr/contexts
    copying opendr/contexts/autogen.py -> build/lib.linux-x86_64-3.7/opendr/contexts
    copying opendr/contexts/__init__.py -> build/lib.linux-x86_64-3.7/opendr/contexts
    copying opendr/contexts/_constants.py -> build/lib.linux-x86_64-3.7/opendr/contexts
    copying opendr/contexts/draw_triangle_shaders_2_1.py -> build/lib.linux-x86_64-3.7/opendr/contexts
    creating build/lib.linux-x86_64-3.7/opendr/test_dr
    copying opendr/test_dr/__init__.py -> build/lib.linux-x86_64-3.7/opendr/test_dr
    running build_ext
    building 'opendr.contexts.ctx_mesa' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/opendr
    creating build/temp.linux-x86_64-3.7/opendr/contexts
    gcc -pthread -B /home/SERILOCAL/l.gagliano/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D__OSMESA__=1 -Iopendr/contexts -I. -I/home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include -Iopendr/contexts/OSMesa/include -I/home/SERILOCAL/l.gagliano/anaconda3/include/python3.7m -c opendr/contexts/ctx_mesa.c -o build/temp.linux-x86_64-3.7/opendr/contexts/ctx_mesa.o -lstdc++
    In file included from /home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:0,
                     from /home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from opendr/contexts/ctx_mesa.c:660:
    /home/SERILOCAL/l.gagliano/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from opendr/contexts/ctx_mesa.c:663:0:
    opendr/contexts/OSMesa/include/GL/osmesa.h:258:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     typedef void (*OSMESAproc)();
     ^
    opendr/contexts/ctx_mesa.c: In function ‘__pyx_pf_6opendr_8contexts_8ctx_mesa_13OsContextBase_150ShaderSource’:
    opendr/contexts/ctx_mesa.c:12788:49: warning: passing argument 3 of ‘glShaderSource’ from incompatible pointer type [-Wincompatible-pointer-types]
       glShaderSource(__pyx_v_shader, __pyx_v_count, (&__pyx_v_s), (&__pyx_v_len));
                                                     ^
    In file included from opendr/contexts/OSMesa/include/GL/gl.h:2085:0,
                     from opendr/contexts/gl_includes.h:10,
                     from opendr/contexts/ctx_mesa.c:662:
    opendr/contexts/OSMesa/include/GL/glext.h:5794:21: note: expected ‘const GLchar ** {aka const char **}’ but argument is of type ‘char **’
     GLAPI void APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar* *string, const GLint *length);
                         ^
    gcc -pthread -shared -B /home/SERILOCAL/l.gagliano/anaconda3/compiler_compat -L/home/SERILOCAL/l.gagliano/anaconda3/lib -Wl,-rpath=/home/SERILOCAL/l.gagliano/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/opendr/contexts/ctx_mesa.o -Lopendr/contexts/OSMesa/lib -lOSMesa -lGL -lGLU -o build/lib.linux-x86_64-3.7/opendr/contexts/ctx_mesa.cpython-37m-x86_64-linux-gnu.so -lstdc++
    /home/SERILOCAL/l.gagliano/anaconda3/compiler_compat/ld: cannot find -lOSMesa
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/SERILOCAL/l.gagliano/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7le0ae6k/opendr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-31er561u/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-7le0ae6k/opendr/

```

**Comment by lukkio88** [comment]
In that case at some point I come across:

```
Failed building wheel for opendr
```

Some other stuff goes through, but I end up with:

```
Command "/home/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7le0ae6k/opendr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-31er561u/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-7le0ae6k/opendr/
```

**Comment by anuragranj** [comment]
Could you try installing opendr from here and check?
https://github.com/mattloper/opendr

**Comment by lukkio88** [comment]
Let me try, I'll get back to you

**Comment by lukkio88** [comment]
There's no guide on how to install it. I've tried the `pip install -r requirements.txt` but I'm getting:

```
Obtaining file:///home/Projects/opendr (from -r requirements.txt (line 2))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/Projects/opendr/setup.py", line 152, in <module>
        main()
      File "/home/Projects/opendr/setup.py", line 141, in main
        download_osmesa()
      File "/home/Projects/opendr/setup.py", line 43, in download_osmesa
        wget('http://files.is.tue.mpg.de/mloper/opendr/osmesa/%s' % (osmesa_fname,), dest_fname=zip_fname)
      File "/home/Projects/opendr/opendr/utils.py", line 37, in wget
        open(dest_fname, 'w').write(contents)
    TypeError: write() argument must be str, not bytes
    Downloading OSMesa.Linux.x86_64.zip
    http://files.is.tue.mpg.de/mloper/opendr/osmesa/OSMesa.Linux.x86_64.zip
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/Projects/opendr/
```

**Comment by anuragranj** [comment]
Are you using python2.7 or python3?

**Comment by lukkio88** [comment]
python3

**Comment by anuragranj** [comment]
Oh, so [opendr](https://github.com/mattloper/opendr) doesnt support python3, same for [MPI-IS/mesh](https://github.com/MPI-IS/mesh). I think it would be more convenient if you use python2.7. MPI-IS/mesh is expected to be python3 friendly in future, and we will update the code then to support python3 as well.

**Comment by Dawars** [comment]
There is an unofficial **opendr** (https://github.com/polmorenoc/opendr) port for Python 3 and I'm working on porting the mesh lib...
It's definitely more work but sooner or later it has to be done.

**Comment by anuragranj** [comment]
Thanks @Dawars . Could you send the pull request to mesh lib once the port is complete?

**Comment by eng100200** [comment]
@lukkio88  hello lukkio did you resolve the opendr issue?

**Comment by lukkio88** [comment]
My apologies for the late reply. No I didn't manage. But I would be very happy if I could manage.

**Comment by Raji42** [comment]
Im Getting below error when i try to install "pip install -r requirements.txt",Please help me

C:\Users\Thanush\github\cp-barebone-movie-app-final (step_11_final_movie_app -> origin)
λ  pip install -r requirements.txt
Collecting airtable-python-wrapper==0.8.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a2/5f/13d016710c494ff07da8e5d62f845d0abd3fe3bb35444624258d51182f9f/airtable_python_wrapper-0.8.0-py2.py3-none-any.whl
Collecting certifi==2018.1.18 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fa/53/0a5562e2b96749e99a3d55d8c7df91c9e4d8c39a9da1f1a49ac9e4f4b39f/certifi-2018.1.18-py2.py3-none-any.whl
Requirement already satisfied: chardet==3.0.4 in c:\users\thanush\anaconda3\lib\site-packages (from -r requirements.txt (line 3)) (3.0.4)
Collecting Django==2.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/44/98/35b935a98a17e9a188efc2d53fc51ae0c8bf498a77bc224f9321ae5d111c/Django-2.0-py3-none-any.whl (7.1MB)
    2% |█                               | 174kB 2.1kB/s eta 0:53:48Exception:
Traceback (most recent call last):
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 360, in _error_catcher
    yield
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\Thanush\Anaconda3\lib\http\client.py", line 447, in read
    n = self.readinto(b)
  File "C:\Users\Thanush\Anaconda3\lib\http\client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Thanush\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Thanush\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Thanush\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 334, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\download.py", line 878, in unpack_url
    progress_bar=progress_bar
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\download.py", line 702, in unpack_http_url
    progress_bar)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\download.py", line 946, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\download.py", line 639, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\utils\hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\download.py", line 607, in written_chunks
    for chunk in chunks:
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\utils\ui.py", line 159, in iter
    for x in it:
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_internal\download.py", line 596, in resp_read
    decode_content=False):
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Thanush\Anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Thanush\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by redredbluee** [comment]
Hi, I use python2.7 for this project and I installed opendr, but I cannot install MPI/Mesh. I found the mesh package requires python3.5+ right now and maybe that is why I cannot compile it . How could I install mesh in python2.7?   Looking forward for your reply.
