### ISSUE TITLE
opendr issue

### ISSUE THREAD

**Issue by sunit1409** [anuragranj/coma#16]
python main.py --data data/processed/sliced --name sliced

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from lib import models, graph, coarsening, utils, mesh_sampling
  File "/home/dl/coma/lib/mesh_sampling.py", line 8, in <module>
    from opendr.topology import get_vert_connectivity, get_vertices_per_edge
ImportError: No module named opendr.topology

**Comment by sunit1409** [comment]
> python main.py --data data/processed/sliced --name sliced
> 
> Traceback (most recent call last):
> File "main.py", line 2, in 
> from lib import models, graph, coarsening, utils, mesh_sampling
> File "/home/dl/coma/lib/mesh_sampling.py", line 8, in 
> from opendr.topology import get_vert_connectivity, get_vertices_per_edge
> ImportError: No module named opendr.topology

this  issue pops up when opendr does not get installed as stated in the requirements file.
